### ISSUE TITLE
printf error for multibyte UTF8 characters

### ISSUE THREAD

**Issue by Hermann-SW** [raspberrypi/micropython#14]
On Pi400 python this works:
```
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print("a{:c}{:c}{:c}{:c}a".format(0xf0,0x9f,0x91,0x8d))
a👍a
>>> 
```

On Pico Micropython this partially works, thumbs up gets shown in minicom, but there is an additional wrong character:
```Press CTRL-A Z for help on special keys


>>> print("a{:c}{:c}{:c}{:c}a".format(0xf0,0x9f,0x91,0x8d))
að👍a
>>> 
```

**Comment by lurch** [comment]
Have you confirmed that this is definitely a bug with Pico Micropython rather than minicom? When dealing with multibyte UTF8 it's sometimes hard to work out exactly where in the chain from CPU -> .... -> Monitor that things are actually going wrong :wink: 

Oh, and I've only just realised you've filed this against the https://github.com/raspberrypi/micropython repo. MicroPython has been merged upstream, so you should report this at https://github.com/micropython/micropython (closing the issue here).
